{"run_number": "1714489496196859", "step_name": "data_preprocess", "task_id": "2", "attempt_id": 0, "name": "_exception", "content_type": "gzip+pickle-v2", "type": "metaflow.artifact", "sha": "f3627f46179fdd95bf0e83101840fd1d71b60e40", "ds_type": "local", "location": ":root:/home/sammy/Documents/Flutter Projects/Django Server by Ananat/ML_Ops_Mess-Management-System/Django_ML_Server/mess_system_project/static/mess_system_app/.metaflow", "flow_id": "DataPreparation", "user_name": "sammy", "tags": [], "system_tags": ["runtime:dev", "metaflow_version:2.11.10", "user:sammy", "python_version:3.11.6"], "ts_epoch": 1714489496979}